name: CI - Build Compiler Bundle

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'compiler/**'
      - 'droe'
      - 'run.js'
      - '*.py'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Create compiler bundle
      run: |
        # Create the main compiler bundle
        tar -czf compiler.tar.gz compiler/ droe run.js
        echo "✅ Compiler bundle created"
        ls -lh compiler.tar.gz
    
    - name: Generate checksums
      run: |
        sha256sum compiler.tar.gz > compiler.tar.gz.sha256
        echo "✅ Checksums generated:"
        cat *.sha256
    
    - name: Upload compiler bundle as artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiler-bundle-${{ github.sha }}
        path: |
          compiler.tar.gz
          compiler.tar.gz.sha256
        retention-days: 30
    
    - name: Upload latest compiler bundle
      uses: actions/upload-artifact@v4
      with:
        name: compiler-bundle-latest
        path: |
          compiler.tar.gz
          compiler.tar.gz.sha256
        retention-days: 7